FROM quay.balgroupit.com/baloise-base-images/openjdk:8-jdk-slim
VOLUME /tmp
COPY event-listener/target/event-listener*.jar app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
